services:  
  easyproxy:
    build: https://github.com/realbestia1/EasyProxy.git#main
    container_name: easyproxy
    restart: unless-stopped
    shm_size: "1gb"
    depends_on:
      - byparr
    ports:
      - '${PORT:-7860}:${PORT:-7860}' #modifica la variabile "PORT" per cambiare la porta
    environment:
      - API_PASSWORD=ep      #qui inserisci la tua password personalizzata
      - PORT=7860
      - BYPARR_URL=http://byparr:8191
      - BYPARR_TIMEOUT=30
      #- WORKERS=2            # Se commentato, usa il numero di core della CPU (nproc)
      
      # Scegli come gestire gli stream MPD/DASH:
      # - ffmpeg: Transcoding via FFmpeg (richiede FFmpeg installato, alta CPU ma sync A/V migliore)
      # - legacy: Usa mpd_converter + drm_decrypter (più leggero ma possibili problemi di compatibilità)
      #- MPD_MODE=legacy
      
      # VARIABILI OPZIONALI
      
      # --- Proxy Globale ---
      # Usato per tutte le richieste che non hanno una regola specifica in TRANSPORT_ROUTES.
      # Esempio: GLOBAL_PROXY=http://myproxy.com:8080
      #- GLOBAL_PROXY=
      
      # --- Regole di Trasporto (TRANSPORT_ROUTES) ---
      # Sistema avanzato per routing proxy basato su URL patterns.
      # Formato: {URL=pattern, PROXY=proxy_url, DISABLE_SSL=true}, {URL=pattern2, PROXY=proxy_url2, DISABLE_SSL=true}
      # - URL: pattern da cercare nell'URL (es. vavoo.to, dlhd.dad, giokko.ru)
      # - PROXY: proxy da usare (lascia vuoto per connessione diretta)
      # - DISABLE_SSL: per disattivare la verifica ssl
      
      #- TRANSPORT_ROUTES={URL=vavoo.to, PROXY=socks5://proxy1:1080, DISABLE_SSL=true}, {URL=dlhd.dad, PROXY=http://proxy2:8080, DISABLE_SSL=true}

  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    restart: unless-stopped
    init: true
    # Per usare Byparr all'esterno del network interno, decommenta le porte:
    # ports:
    #   - "8191:8191"
